// Generated by CoffeeScript 1.6.3
(function() {
  var releasy, should, steps;

  should = require('should');

  releasy = require('../releasy.js');

  steps = require('../libs/steps.js');

  describe('steps', function() {
    return it('should exist', function(done) {
      steps.should.be.ok;
      return done();
    });
  });

  describe('releasy', function() {
    return it('should exist', function(done) {
      releasy.should.be.ok;
      return done();
    });
  });

}).call(this);

/*
//@ sourceMappingURL=test.map
*/
